tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface": "#faf8ff",
                "surface-container": "#eaedff",
                "on-tertiary-fixed-variant": "#3323cc",
                "on-primary": "#ffffff",
                "on-surface-variant": "#434656",
                "on-primary-container": "#e3e6ff",
                "primary-fixed": "#dce1ff",
                "secondary": "#006875",
                "surface-container-low": "#f2f3ff",
                "surface-variant": "#dae2fd",
                "primary-container": "#0055ff",
                "on-secondary-fixed": "#001f24",
                "surface-container-high": "#e2e7ff",
                "border-subtle": "#E2E8F0",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#faf8ff",
                "secondary-fixed": "#9cf0ff",
                "error-container": "#ffdad6",
                "surface-gray": "#F8FAFC",
                "surface-tint": "#004dea",
                "error": "#ba1a1a",
                "status-cyan": "#22D3EE",
                "on-primary-fixed": "#001551",
                "secondary-container": "#00e3fd",
                "tertiary-container": "#574fed",
                "on-tertiary": "#ffffff",
                "on-tertiary-fixed": "#0f0069",
                "surface-dim": "#d2d9f4",
                "secondary-fixed-dim": "#00daf3",
                "on-secondary-container": "#00616d",
                "outline": "#737688",
                "inverse-surface": "#283044",
                "tertiary": "#3d31d4",
                "inverse-primary": "#b6c4ff",
                "primary": "#0041c8",
                "surface-container-highest": "#dae2fd",
                "background": "#faf8ff",
                "on-surface": "#131b2e",
                "on-primary-fixed-variant": "#0039b3",
                "tertiary-fixed-dim": "#c3c0ff",
                "inverse-on-surface": "#eef0ff",
                "tertiary-fixed": "#e2dfff",
                "code-indigo": "#312E81",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#b6c4ff",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-background": "#131b2e",
                "on-secondary-fixed-variant": "#004f58",
                "on-tertiary-container": "#e8e5ff",
                "outline-variant": "#c3c5d9"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "section-padding": "96px",
                "container-max": "1200px",
                "unit": "8px",
                "gutter": "24px",
                "card-padding": "24px"
            },
            fontFamily: {
                "headline-md": ["Montserrat"],
                "headline-xl-mobile": ["Montserrat"],
                "label-md": ["JetBrains Mono"],
                "headline-lg-mobile": ["Montserrat"],
                "headline-xl": ["Montserrat"],
                "headline-lg": ["Montserrat"],
                "body-md": ["Inter"],
                "code-sm": ["JetBrains Mono"],
                "body-lg": ["Inter"]
            },
            fontSize: {
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "headline-xl-mobile": ["32px", { lineHeight: "1.1", fontWeight: "700" }],
                "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
                "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
                "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                "code-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
            }
        }
    }
};
